<?php

namespace Database\Factories;

use App\Models\Stan;
use App\Models\Vlasnik;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<Vlasnik>
 */
class VlasnikFactory extends Factory
{
    /**
     * Define the model's default state.
     * The access token is generated by the model on create.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'stan_id' => Stan::factory(),
            'ime' => fake()->firstName(),
            'prezime' => fake()->lastName(),
            'email' => fake()->unique()->safeEmail(),
            'telefon' => fake()->numerify('06########'),
            'aktivan' => true,
        ];
    }

    /**
     * Deactivated owner (no access).
     */
    public function neaktivan(): static
    {
        return $this->state(fn (array $attributes) => ['aktivan' => false]);
    }
}
